### ISSUE TITLE
ModuleNotFoundError: No module named 'sample_standard_app'

### ISSUE THREAD

**Issue by zhangtianhong-1998** [alipay/agentUniverse#126]
想debug一下discussion_chat_bots.py 但是显示找不到

**Comment by LandJerry** [comment]
> 想debug一下discussion_chat_bots.py 但是显示找不到

和你的项目名称和路径有关系，如果你把对应的文件目录改名了，在

config/config.toml

包扫描路径里需要对应修改。

![image](https://github.com/user-attachments/assets/704585ea-8dac-45b0-a420-9bc515752a0a)

**Comment by cainiaogoroad** [comment]
我没改啊，为什么也会显示
![image](https://github.com/user-attachments/assets/a9e74e17-614d-4a02-970e-b48bd06da389)
