### ISSUE TITLE
自定义Agent

### ISSUE THREAD

**Issue by zhangtianhong-1998** [alipay/agentUniverse#127]
您好，我最近在阅读你们的实现源码，我关注到你们的ReacAgent实现本质上调用了langchain中ReacAgent，并且其他agent也是根据LECL实现，由于langchain中封装比较严重，如果我想重写RecAgent在链中注入停止的词例如{"stop":['Obeservation']}，这一次需要如何实现，不知道是否能够提供相关建议

**Comment by zhangtianhong-1998** [comment]
之前也看过modelscope-agent，相较于这个基于langchain的LECL工作流，更隐蔽，对二次开发的难度会大一点，所以有点困惑

**Comment by LandJerry** [comment]
> 您好，我最近在阅读你们的实现源码，我关注到你们的ReacAgent实现本质上调用了langchain中ReacAgent，并且其他agent也是根据LECL实现，由于langchain中封装比较严重，如果我想重写RecAgent在链中注入停止的词例如{"stop":['Obeservation']}，这一次需要如何实现，不知道是否能够提供相关建议

stop注入这个功能我们已经关注到了，我们会在近期的迭代中把这部分能力开放出去。如果你本身对于langchain的技术栈非常熟悉，你可以覆写自定义agent的execute方法中直接按照langchain的写法使用，这样在编写ReactAgent体验就和使用langchain相似了。

**Comment by LandJerry** [comment]
> 您好，我最近在阅读你们的实现源码，我关注到你们的ReacAgent实现本质上调用了langchain中ReacAgent，并且其他agent也是根据LECL实现，由于langchain中封装比较严重，如果我想重写RecAgent在链中注入停止的词例如{"stop":['Obeservation']}，这一次需要如何实现，不知道是否能够提供相关建议

这个功能已经在v0.0.13版本中支持，感谢您的关注。

**Comment by darvsum** [comment]
![image](https://github.com/user-attachments/assets/07dd3667-2a22-4973-96ab-c55f578f2ce6)
react这个地方是不是写错了？
需要在两个地方配置stop_sequence吗？

还有我即使配置了stop_sequence,执行react仍然报错。1、Invalid Format: Missing 'Action:' after 'Thought:  2、遍历完15次后，Agent stopped due to iteration limit or time limit.

**Comment by darvsum** [comment]
![image](https://github.com/user-attachments/assets/07dd3667-2a22-4973-96ab-c55f578f2ce6)
react这个地方是不是写错了？
需要在两个地方配置stop_sequence吗？

还有我即使配置了stop_sequence,执行react仍然报错。1、Invalid Format: Missing 'Action:' after 'Thought:  2、遍历完15次后，Agent stopped due to iteration limit or time limit.

**Comment by darvsum** [comment]
> ![image](https://private-user-images.githubusercontent.com/4550512/391228175-07dd3667-2a22-4973-96ab-c55f578f2ce6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NjE1NzksIm5iZiI6MTczMjk2MTI3OSwicGF0aCI6Ii80NTUwNTEyLzM5MTIyODE3NS0wN2RkMzY2Ny0yYTIyLTQ5NzMtOTZhYi1jNTVmNTc4ZjJjZTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMzBUMTAwNzU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmY3MzQ2OGVhNTZjMmRmYWFhNGFhNTQ0ZmZmMWYxNmNhYmM0MDNkNzI0YjJmMjI2NGM0NTdlMjAxZDk5OWU3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.gwDIZJBgrZP_9B5_pQHUNCPzwta8JoBy1Y1rXq-C9eY) react这个地方是不是写错了？ 需要在两个地方配置stop_sequence吗？
> 
> 还有我即使配置了stop_sequence,执行react仍然报错。1、Invalid Format: Missing 'Action:' after 'Thought: 2、遍历完15次后，Agent stopped due to iteration limit or time limit.

我的stop word是    
  - "Observation:"
  - "Observation:\n"
