### ISSUE TITLE
system_db_uri默认路径问题

### ISSUE THREAD

**Issue by z4656207** [alipay/agentUniverse#142]
启动product_application.py，config.toml中system_db_uri默认未配置，数据库默认路径代码如下：
class RequestLibrary:
system_db_uri = f'sqlite:////{db_path}'
这个路径在windows下多了一个/（未在linux下测试），导致无法打开sqlite，
解决方法：
配置绝对路径，如system_db_uri = 'sqlite:///D:\\github\\agentUniverse\\sample_standard_app\\DB\\agent_universe.db'，
或在源码中删除一个/修复bug

**Comment by seetimee** [comment]
同样的问题,我直接设成system_db_uri = 'sqlite:///agent_universe.db'

**Comment by LandJerry** [comment]
> 启动product_application.py，config.toml中system_db_uri默认未配置，数据库默认路径代码如下： class RequestLibrary: system_db_uri = f'sqlite:////{db_path}' 这个路径在windows下多了一个/（未在linux下测试），导致无法打开sqlite， 解决方法： 配置绝对路径，如system_db_uri = 'sqlite:///D:\github\agentUniverse\sample_standard_app\DB\agent_universe.db'， 或在源码中删除一个/修复bug

感谢您的提出，v0.0.13版本已经修复。
