### ISSUE TITLE
照着demo跑完全跑不同

### ISSUE THREAD

**Issue by seetimee** [alipay/agentUniverse#158]
https://github.com/alipay/agentUniverse/blob/master/docs/guidebook/zh/6_4_1_%E9%87%91%E8%9E%8D%E4%BA%8B%E4%BB%B6%E5%88%86%E6%9E%90%E6%A1%88%E4%BE%8B.md
请问文件结构到底应该怎样设置，运行时到底要cmd到哪里，如何判断openai_base变量是否生效了(老是显示我的key错误)

**Comment by LandJerry** [comment]
是不是用的vscode，vscode的python初始化会比较麻烦；如果需要详细的设置方式，可以进答疑群。pycharm的环境配置方便一些

**Comment by seetimee** [comment]
跑通啦,这是踩坑博客:https://mp.csdn.net/mp_blog/creation/success/142049174

**Comment by LandJerry** [comment]
> 跑通啦,这是踩坑博客:https://blog.csdn.net/stephen147/article/details/142049174?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22142049174%22%2C%22source%22%3A%22stephen147%22%7D

quickstart正在改版，最近几天会更新成按照用例引导。几个坑我们在文档里会重新引导，感谢分享。
