### ISSUE TITLE
请问我们单独下载sample_standard_app ， 其中的knowledgebase 是不是要初始化，又提示：

### ISSUE THREAD

**Issue by mymoonsoft** [alipay/agentUniverse#189]
2024-11-07 00:03:53.157 | ERROR    | [default] | agentuniverse.agent.action.knowledge.knowledge:query_knowledge:190 | Exception occurred in knowledge query: 'NoneType' object has no attribute 'query' 2024-11-07 00:03:53.157 | ERROR    | [default] | agentuniverse.agent.action.knowledge.knowledge:query_knowledge:190 | Exception occurred in knowledge query: __enter__

尽管出错提示，可以运行得到结果

我认为是不是要初始化一下

**Comment by LandJerry** [comment]
这个是运行官方案例出现的？还是自己定制的knowledge出现的？能否提供更多信息？

**Comment by mymoonsoft** [comment]
就是直接下载了这个sample_standard_app&nbsp; ，我的电话 13724307509，我要用这个来做税务筹划



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jerry Z ***@***.***&gt;; 
发送时间: 2024年11月8日(星期五) 下午2:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alipay/agentUniverse] 请问我们单独下载sample_standard_app ， 其中的knowledgebase 是不是要初始化，又提示： (Issue #189)














 
这个是运行官方案例出现的？还是自己定制的knowledge出现的？能否提供更多信息？

**Comment by AniviaTn** [comment]
这个是由于新版本agentUniverse启动方式和旧版本测试案例兼容性导致的问题，当不启动agenetUniverse的webserver时，您需要在AgentUniverse实例启动时加入core_mode=True的参数，如AgentUniverse().start(config_path='../../config/config.toml', core_mode=True)来保证所有实例加载成功。  该法律案例的问题已经在当前测试版本中修复，您可以先手动在旧版本中添加该参数保证正常运行

**Comment by mymoonsoft** [comment]
感谢，可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alipay/agentUniverse"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月8日(星期五) 下午2:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alipay/agentUniverse] 请问我们单独下载sample_standard_app ， 其中的knowledgebase 是不是要初始化，又提示： (Issue #189)





 
这个是由于新版本agentUniverse启动方式和旧版本测试案例兼容性导致的问题，当不启动agenetUniverse的webserver时，您需要在AgentUniverse实例启动时加入core_mode=True的参数，如AgentUniverse().start(config_path='../../config/config.toml', core_mode=True)来保证所有实例加载成功。  该法律案例的问题已经在当前测试版本中修复，您可以先手动在旧版本中添加该参数保证正常运行
