### ISSUE TITLE
非常奇怪，我用的是react_chat_bot.py，咨询一个会计处理问题，可是搜出来一些巴菲特的结果，当然最后也给出了会计处理问题的结果，我需要在哪儿设置一下正确搜索

### ISSUE THREAD

**Issue by mymoonsoft** [alipay/agentUniverse#192]
Action: google_search_tool
Action Input: 会计准则 租赁收入确认原则 分成模式处理方法
巴菲特旗下的伯克希尔·哈撒韦公司自2022年8月24日首次减持比亚迪股票以来，已经披露了13次减持行为，包括2022年9月1日、11月1日、11月8日、11月17日、12 月8日、2023年1月3日、1月27日、2月9日、3月31日、5月2日等时间点。
最近的一次减持是在2023年10月25日，当时伯克希尔·哈撒韦公司出售82.05万比亚迪H股，使其持股比例降至7.98%。
这次减持的平均价格为每股245.86港元，但整体来看，比亚迪的股价并未受到太大影响。

巴菲特的投资策略包括：
1. 长期投资：巴菲特主张买入并持有优质股票，而非短期交易。他的投资策略往往以做多绩优股为主，不排除出现长期慢牛的可能。
2. 价值投资：巴菲特注重企业的内在价值，而不是短期的股价波动。他会深入研究公司的基本面，包括其盈利能力、市场地位、管理层质量等。
3. 能力圈原则：巴菲特建议投资者只投资于自己理解的领域，即自己的“能力圈”内。这样可以更好地评估企业的真实价值和未来前景。
巴菲特的减持并不会改变比亚迪公司优质的基本面，比亚迪依然是中国新能源汽车行业的龙头。

**Comment by LandJerry** [comment]
你好，案例使用了google_search_tool工具，需要申请key并且填写到框架中。如果没有配置key，框架默认mock了巴菲特相关的数据作为初始化体验。

申请和配置过程，参考这个文档第一部分
https://github.com/alipay/agentUniverse/blob/master/docs/guidebook/zh/2_2_3_%E9%9B%86%E6%88%90%E7%9A%84%E5%B7%A5%E5%85%B7.md

**Comment by LandJerry** [comment]
“最后也给出了会计处理问题的结果”，意味着完全使用了agent模型的通识能力，而没有走公开的检索。申请SERPER_API_KEY后可以看到，如果有其他的检索工具也可以替换使用。

**Comment by mymoonsoft** [comment]
请问，我能否忽略这个工具，只使用langchain&nbsp;的 DuckDuckGoSearchRun&nbsp;工具


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alipay/agentUniverse"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月15日(星期五) 下午5:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alipay/agentUniverse] 非常奇怪，我用的是react_chat_bot.py，咨询一个会计处理问题，可是搜出来一些巴菲特的结果，当然最后也给出了会计处理问题的结果，我需要在哪儿设置一下正确搜索 (Issue #192)





 
“最后也给出了会计处理问题的结果”，意味着完全使用了agent模型的通识能力，而没有走公开的检索。申请SERPER_API_KEY后可以看到，如果有其他的检索工具也可以替换使用。

**Comment by LandJerry** [comment]
> 请问，我能否忽略这个工具，只使用langchain&nbsp;的 DuckDuckGoSearchRun&nbsp;工具
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alipay/agentUniverse" ***@***.***&gt;; 发送时间:&nbsp;2024年11月15日(星期五) 下午5:16 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [alipay/agentUniverse] 非常奇怪，我用的是react_chat_bot.py，咨询一个会计处理问题，可是搜出来一些巴菲特的结果，当然最后也给出了会计处理问题的结果，我需要在哪儿设置一下正确搜索 (Issue #192) “最后也给出了会计处理问题的结果”，意味着完全使用了agent模型的通识能力，而没有走公开的检索。申请SERPER_API_KEY后可以看到，如果有其他的检索工具也可以替换使用。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


可以的直接配置就好，我在另一个issue回复

**Comment by LandJerry** [comment]
已解决，见 https://github.com/alipay/agentUniverse/issues/193
