### ISSUE TITLE
请问如何我配置忽略google_search_tool工具，只使用langchain 的 DuckDuckGoSearchRun 工具

### ISSUE THREAD

**Issue by mymoonsoft** [alipay/agentUniverse#193]

**Comment by LandJerry** [comment]
info:
  name: 'demo_rag_agent'
  description: 'demo rag agent'
profile:
  prompt_version: demo_rag_agent.cn
  llm_model:
    name: 'qwen_llm'
action:
  tool:
    - 'duckduckgo_search'
  knowledge:
memory:
  name: 'demo_memory_a'
metadata:
  type: 'AGENT'
  module: 'agentuniverse.agent.template.rag_agent_template'
  class: 'RagAgentTemplate'


参考这个配置，直接把你使用的agent中的工具列表替换成duckduckgo_search即可。
agentUniverse/sample_standard_app/intelligence/agentic/agent/agent_instance/rag_agent_case/demo_rag_agent.yaml

**Comment by LandJerry** [comment]
> _No description provided._

> info: name: 'demo_rag_agent' description: 'demo rag agent' profile: prompt_version: demo_rag_agent.cn llm_model: name: 'qwen_llm' action: tool: - 'duckduckgo_search' knowledge: memory: name: 'demo_memory_a' metadata: type: 'AGENT' module: 'agentuniverse.agent.template.rag_agent_template' class: 'RagAgentTemplate'
> 
> 参考这个配置，直接把你使用的agent中的工具列表替换成duckduckgo_search即可。 agentUniverse/sample_standard_app/intelligence/agentic/agent/agent_instance/rag_agent_case/demo_rag_agent.yaml

![image](https://github.com/user-attachments/assets/2bb59234-cc67-4224-a6be-238dfa1afb48)
