### ISSUE TITLE
ModuleNotFoundError: No module named 'agentuniverse'

### ISSUE THREAD

**Issue by LittleEnough** [alipay/agentUniverse#55]
hi, When I followed the document:https://github.com/alipay/agentUniverse/blob/master/docs/guidebook/en/1_3_Quick_Start.md 
 step by step  , I encountered an error:
ModuleNotFoundError: No module named 'agentuniverse'

python3 server_application.py 
Traceback (most recent call last):
  File "/opt/agentUniverse/sample_standard_app/app/bootstrap/server_application.py", line 8, in <module>
    from agentuniverse.agent_serve.web.web_booster import start_web_server
ModuleNotFoundError: No module named 'agentuniverse'

Maybe I miss any key settings or something？

**Comment by LandJerry** [comment]
> hi, When I followed the document:https://github.com/alipay/agentUniverse/blob/master/docs/guidebook/en/1_3_Quick_Start.md step by step , I encountered an error: ModuleNotFoundError: No module named 'agentuniverse'
> 
> python3 server_application.py Traceback (most recent call last): File "/opt/agentUniverse/sample_standard_app/app/bootstrap/server_application.py", line 8, in from agentuniverse.agent_serve.web.web_booster import start_web_server ModuleNotFoundError: No module named 'agentuniverse'
> 
> Maybe I miss any key settings or something？

The agentUniverse is not installed; you can try using the pip install command in your env.

```
pip install agentUniverse
```

**Comment by zzw1123** [comment]
I want to use the repo to develop my own applications, so I git clone this project to my local directory. 
Should I pip install agentuniverse?
