### ISSUE TITLE
call service error：Worker (pid:30345) was sent SIGKILL! Perhaps out of memory?

### ISSUE THREAD

**Issue by takkaman** [alipay/agentUniverse#57]
after run python server_application.py, the server cannot work properly.

![image](https://github.com/alipay/agentUniverse/assets/19723559/cab56b68-4eea-4035-8eb3-1843f8a7e49e)

use curl to call demo service，but always return error:
curl http://127.0.0.1:8000/service_run -X POST --header "Content-Type: application/json;charset=UTF-8" -d '{"service_id":"demo_service", "params":{"input":"Your input text here"}}'

curl: (52) Empty reply from server

Also another problem:
the project cannot be closed properly after started, hang at shutting down
[2024-05-30 17:12:26 +0800] [30341] [INFO] Shutting down: Master

Please help to check what's the problem.
Thanks.

**Comment by AniviaTn** [comment]
In higher versions of macOS, Apple has introduced a stricter security mechanism to prevent unsafe behavior when calling Objective-C objects after forking, which has caused conflicts with gunicorn. You can resolve this by:

- Setting the environment variable: export `OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES`
- If you are using PyCharm, you can refer to the following image:
![lQLPJxIGn9CwHP3NAtzNAxSwoEOB6kXhDB4GQ8MHdjp8AQ_788_732](https://github.com/alipay/agentUniverse/assets/30255304/8a998283-6eb1-439e-8a3f-d26c99e1ded2)
![lQLPKGYqjngg7P3NAdXNBdywJ78D-KjBBT0GQ8MHdjp8AA_1500_469](https://github.com/alipay/agentUniverse/assets/30255304/d285b3d8-3907-45a0-b757-e17d87cee099)

We will set flask as default web server on mac platform in our next version,  and user can switch between flask and gunicorn with extra param in start_web_server
