### ISSUE TITLE
curl service return openai related invalid_api_key error, while explicitly set llm to qwen

### ISSUE THREAD

**Issue by takkaman** [alipay/agentUniverse#61]
![image](https://github.com/alipay/agentUniverse/assets/19723559/1a64f9e1-4473-43d6-b4c7-aaf3d6677893)

I try to use default demo_llm which is vis open ai, but curl hang with no response.
Then I try to use qwen_llm as set above, but system still return openai related error, did I modify yaml correctly?

Also another question, any sample to use agent via qwen_llm? Should I still need to provide some kind of key or something else?

Thanks.

**Comment by weizjajj** [comment]
The Qwen large model is compatible with the OpenAI API. please refer: https://help.aliyun.com/zh/dashscope/developer-reference/compatibility-of-openai-with-dashscope/?spm=a2c4g.11186623.0.i3
