### ISSUE TITLE
Hey, was "支小助" built using agentUniverse? If so, what model does it use?

### ISSUE THREAD

**Issue by willchen0729** [alipay/agentUniverse#90]

**Comment by LandJerry** [comment]
"ZHI XIAO ZHU" is built using agentUniverse, which utilizes a privately developed internal LLM by Alipay.

**Comment by LandJerry** [comment]
> _No description provided._


"ZHI XIAO ZHU" is built using agentUniverse, which utilizes a privately developed internal LLM by Alipay.
